# Generated by Django 3.2.25 on 2026-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='field',
            field=models.CharField(blank=True, default='', help_text='e.g. Engineering, Arts, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, default='', help_text='e.g. Bachelors, Masters, PhD', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(blank=True, default='', help_text='e.g. Full Tuition, $10,000, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
