# Generated by Django 3.2.25 on 2026-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_alter_scholarship_min_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholarships/'),
        ),
    ]
