# Generated by Django 3.2.25 on 2026-07-28 17:15

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20260705_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_fields',
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, help_text='Academic or professional achievements'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise_areas',
            field=models.CharField(blank=True, help_text='e.g. Europe, PhD, STEM', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gre_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ielts_score',
            field=core.fields.SafeDecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_ai_reset',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='major_course',
            field=models.CharField(blank=True, help_text='e.g. Computer Science', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentorship_bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Comma separated interests (e.g. AI, IoT)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='scholar_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='List of skills (comma separated)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academic_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cgpa',
            field=core.fields.SafeDecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
