# Generated by Django 3.2.25 on 2026-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scholarship_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
