# Generated by Django 3.2.25 on 2026-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, help_text='e.g. Full Tuition, $10,000, etc.', max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
