# Generated by Django 3.2.25 on 2026-07-23 19:50

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20260705_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='min_cgpa',
            field=core.fields.SafeDecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
