# Generated by Django 3.2.25 on 2026-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_scholarship_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
