# Generated by Django 3.2.25 on 2026-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_scholarship_admin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='field',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g. Engineering, Arts, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g. Bachelors, Masters, PhD', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
