# Generated by Django 3.2.25 on 2026-07-23 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarships', '0004_alter_scholarship_min_cgpa'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='file_url',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='academic_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='application_type',
            field=models.CharField(choices=[('Self', 'Self Application'), ('Agency', 'Agency Processing')], default='Self', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='file',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdocument',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Processing', 'Processing'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='scholarshipapplication',
            unique_together={('user', 'scholarship')},
        ),
    ]
