# Generated by Django 3.2.25 on 2026-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20260724_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='applications', to='applications.UserDocument'),
        ),
    ]
