# Generated by Django 3.2.25 on 2026-08-01 16:54

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20260801_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
